### ISSUE TITLE
Curl User Agent Results in 403 Forbidden Error

### ISSUE THREAD

**Issue by phillc73** [burningsoul/API-CLIENT#7]
When making an http GET call via Curl, if the user agent is set to "curl" the result is a 403 Forbidden error.

For example, I'm writing a small [R package to consume astronomy related APIs](https://github.com/phillc73/rinspace). I'm using the httr package for GET/POST, which in turn uses libcurl.

The following R code returns the 403 Forbidden error:
```r
library(httr)

  url = "http://api.burningsoul.in/moon/1456419245"
  httr::GET(url)

```
The user agent here is specifically:  "libcurl/7.47.0 r-curl/0.9.6 httr/1.1.0"

However, if I explicitly set the user agent to mimic a browser, the correct results are returned.

e.g.

```r
library(httr)

  url = "http://api.burningsoul.in/moon/1456419245"
  httr::GET(url,  user_agent("Mozilla/5"))
 
```
User agent is now: "Mozilla/5"

**Comment by aaryadev** [comment]
The server has internal validation for header metadata,which is also used for analytics ,
so it better to set useragent.

I have tried curl in terminal (ubuntu 14) works fine.
