### ISSUE TITLE
data based on position?

### ISSUE THREAD

**Issue by dentex** [burningsoul/API-CLIENT#8]
Hi,
More an info request, than anything else, on the MOON API.
How the returned data change based on observer's position on earth?
(Edited the question because thinking about it, moon phase and illumination don't change on different places on earth, what changes is the moon's visibility on the horizon, isn't it?)

 Thanks

**Comment by aaryadev** [comment]
Hi you are absolutely correct , 
But if you look at 
https://github.com/burningsoul/API-CLIENT/issues/6
here is the code for the moon api

its not location based its time based. its says when moon appear on your location it will be like this.
I am building v2 once its completed it will be location based .

Thanks for showing interest.

**Comment by dentex** [comment]
Ok thanks.
So is it correct that phase and illumination don't change at various places on earth? What changes is the "moonset" or the "moonrise". Right?

**Comment by aaryadev** [comment]
Yes Phase and illumination is based on age of moon, the timing of rise and set depends on location of earth.

**Comment by dentex** [comment]
Great
Il 12/mag/2016 11:08 AM, "Mangalamoorti" <notifications@github.com> ha
scritto:
